name: Build Android APK dari ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Ekstrak File Project ZIP
        run: unzip WarungKu-AndroidIDE.zip -d project_dir

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Gradle Wrapper
        run: |
          cd project_dir
          npm install -g @ionic/cli
          gradle wrapper --gradle-version 8.2

      - name: Build Debug APK
        run: |
          cd project_dir
          ./gradlew assembleDebug

      - name: Upload APK Hasil Compile
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-WarungKu-Debug
          path: project_dir/app/build/outputs/apk/debug/*.apk
